POST https://node-js-api-31z6.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET https://node-js-api-31z6.onrender.com/videos
###

PUT https://node-js-api-31z6.onrender.com/videos/1af52f2d-7d67-47fa-8d48-ecf854420a1d
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o segundo vídeo",
    "duration": 180
}

###

DELETE https://node-js-api-31z6.onrender.com/videos/1af52f2d-7d67-47fa-8d48-ecf854420a1d
